apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: express-gallery
spec:
  containers:
    - name: express
      image: gcr.io/kubernetes-ws-0/hello-world-node
      ports:
        - containerPort: 3000
