apiVersion: v1
kind: Service
metadata:
  name: first-service
  labels:
    app: express-gallery
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http-express
  selector:
    app: express-gallery
