apiVersion: v1
kind: Service
metadata:
  name: main-service
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http-nginx
  selector:
    app: hello-world
