apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
  labels:
    app: redmine
spec:
  replicas: 1
  selector:
    name: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:5.5.46-0-r01
          args:
            - --max_connect_errors=1000
          env:
            - name: MARIADB_DATABASE
              value: redmine_production
            - name: MARIADB_USER
              value: redmine
            - name: MARIADB_PASSWORD
              value: secretpassword
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: <FILL_THIS>
              mountPath: /bitnami/mariadb/data
          livenessProbe:
            tcpSocket:
              port: <FILL_THIS>
            initialDelaySeconds: 30
            timeoutSeconds: 1
      volumes:
        - name: mariadb-persistent-storage
          gcePersistentDisk:
            pdName: <FILL_THIS>
            fsType: ext4
