apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: redmine
spec:
  ports:
    - port: <FILL_THIS>
      targetPort: <FILL_THIS>
      protocol: TCP
  selector:
    name: <FILL_THIS>
