apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: redmine
spec:
  type: <FILL_THIS>
  ports:
    - port: 80
      targetPort: <FILL_THIS>
      protocol: TCP
  selector:
    name: <FILL_THIS>
