apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  replicas: 1
  selector:
    name: redmine
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
        - name: redmine
          image: bitnami/redmine
          env:
            - name: MARIADB_HOST
              value: db
            - name: MARIADB_PASSWORD
              value: secretpassword
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 1
