apiVersion: v1
kind: Pod
metadata:
  name: express-example
  labels:
    app: hello-world
spec:
  containers:
    - name: express
      image: gcr.io/kubernetes-ws-0/hello-world-node
      ports:
        - containerPort: 3000
    - name: nginx
      image: gcr.io/kubernetes-ws-0/hello-world-nginx
      ports:
        - containerPort: 80
