apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    name: redmine
spec:
  replicas: 1
  selector:
    name: redmine
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
        - name: redmine
          image: gcr.io/kubernetes-ws-0/redmine-basic
          env:
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_NAME
              value: redmine_production
            - name: DATABASE_USER
              value: redmine
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: redmine-secrets
              mountPath: /etc/redmine-secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 1
      volumes:
        - name: redmine-secrets
          secret:
            secretName: redmine-secrets
