apiVersion: v1
kind: ReplicationController
metadata:
  name: redmine
  labels:
    name: redmine
spec:
  replicas: 1
  selector:
    name: redmine
  template:
    metadata:
      labels:
        name: redmine
    spec:
      containers:
        - name: redmine
          image: gcr.io/kubernetes-ws-0/redmine-basic
          env:
            - name: REDMINE_SESSION_TOKEN
              value: SUPERLONGANDSECRETSESSIONTOKENFORTHISAPP
            - name: DATABASE_HOST
              value: mariadb
            - name: DATABASE_NAME
              value: redmine_production
            - name: DATABASE_USER
              value: redmine
            - name: DATABASE_PASSWORD
              value: secretpassword
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 1
